"""empty message

Revision ID: 66e6a5177f9c
Revises: 
Create Date: 2021-06-18 14:01:43.224516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e6a5177f9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_feature',
    sa.Column('novel', sa.String(length=30), nullable=False),
    sa.Column('character', sa.String(length=30), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('feature', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('novel', 'character')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_feature')
    # ### end Alembic commands ###
