"""empty message

Revision ID: 9c6061567b7f
Revises: 
Create Date: 2021-09-26 23:37:45.230358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6061567b7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('novel', sa.String(length=30), nullable=False),
    sa.Column('character', sa.String(length=30), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('feature', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('novel', 'character')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    # ### end Alembic commands ###
